package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Cambiar_contrasena extends VerticalLayout {
	protected TextField contrasena_actual_label;
	protected TextField contrasena_nueva_label;
	protected TextField confirmar_contrasena_nueva;
	protected Button boton_confirmar_nuevas_pass;
	protected Button cancelar_nueva_pass;

	public Cambiar_contrasena() {
		Design.read(this);
	}
}
