package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class crear_tema_nuevo_ventana extends VerticalSplitPanel {
	protected TextField texto_nuevo_tema;
	protected TextArea descrpcion_tema_nuevo;
	protected Button boton_cancelar;
	protected Button boton_subir;

	public crear_tema_nuevo_ventana() {
		Design.read(this);
	}
}
