package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class foro_no_registrado_ventana extends VerticalLayout {
	protected Panel boton_menuDefecto;
	protected Label foro_nombre_label;
	protected Button iniciar_sesion;
	protected Button boton_registrarse;
	protected Panel boton_buscar;
	protected TextField textfield_buscar;
	protected FormLayout formLayout_interfaz;
	protected Label label_actual;
	protected VerticalLayout lista_secciones_entrada;
	protected Button boton_antiguedad;
	protected Button boton_valoracion;

	public foro_no_registrado_ventana() {
		Design.read(this);
	}
}
