package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class foro_registrado_ventana extends VerticalLayout {
	protected Panel panel_foro_nombre;
	protected Panel click_perfilUsuario;
	protected Label nombre_tarjeta_user;
	protected Panel boton_buscar;
	protected TextField textfield_buscar;
	protected FormLayout formLayout_interfaz;
	protected Label label_lista_modo;
	protected VerticalLayout layout_Secciones;
	protected Button boton_antiguedad;
	protected Button boton_valorar;
	protected Button boton_crear_seccion;
	protected Button boton_crear_tema;

	public foro_registrado_ventana() {
		Design.read(this);
	}
}
