package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class historail_notificaciones extends VerticalSplitPanel {
	protected HorizontalLayout ventana_user;
	protected Panel etiqueta_user;
	protected Label nombre_user_historial_notificaciones;
	protected Label amigos_var_historial_notificaciones;
	protected Label cantidad_mensajes_var_historial;
	protected FormLayout form_layout_lista;
	protected VerticalLayout lista_items_notificaciones;
	protected Button boton_atender;
	protected Button boton_archivar;
	protected Button boton_denunciar;
	protected Button boton_volver;

	public historail_notificaciones() {
		Design.read(this);
	}
}
