package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class item_secciones_ventana extends VerticalLayout {
	protected Panel panel_item_seccion;
	protected Label label_nombre_seccion;
	protected Button boton_perfil_creador;
	protected VerticalLayout verticalLayout;
	protected Label label_num_megusta;
	protected Label label_num_participantes;

	public item_secciones_ventana() {
		Design.read(this);
	}
}
