package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class item_tema_ventana extends VerticalLayout {
	protected Panel item_panel;
	protected Label nombre_tema_label;
	protected Button boton_visitar_perfil_creador;
	protected Button boton_reportar_item_tema;
	protected Button eliminarTema;
	protected Label label_fecha;
	protected VerticalLayout verticalLayout;
	protected TextArea text_area_descripcion;

	public item_tema_ventana() {
		Design.read(this);
	}
}
