package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class item_notifiacion_ventana extends VerticalLayout {
	protected Label titulo_notificacion;
	protected Label cuerpo_notificacion;
	protected Label usuario_creador;
	protected Label tipo_notificaciones;
	protected Button atender_Notificacion;
	protected Button eliminar_notificacion;

	public item_notifiacion_ventana() {
		Design.read(this);
	}
}
