package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class item_mensaje_tema extends VerticalLayout {
	protected Panel panel_mensaje_dimensiones;
	protected Label usuario_mensaje;
	protected Image incluir_amigo_imga_btn;
	protected Panel panel_boton_like;
	protected Button boton_eliminar_mensaje;
	protected Button boton_creador_perfil_mensaje;
	protected Panel ir_tema_principal_mostrar_solo_en_ultimos_mensajes;
	protected Button boton_responder;
	protected Label texto_titulo;
	protected Button reportar_mensaje_en_item;
	protected Label texto_mansaje;

	public item_mensaje_tema() {
		Design.read(this);
	}
}
