package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class item_notificacion_modificador extends VerticalLayout {
	protected Panel perfil_denunciado;
	protected Label label_denunciado;
	protected Button boton_banear;
	protected Button boton_perdonar_ventana;
	protected Label label_tipoDenuncia;
	protected Label titulo_item_reporte;
	protected TextArea text_Area_informacion;
	protected Panel perfil_denunciante;
	protected Label label_denunciante;
	protected Label label_fecha;
	protected Label texto_auxiliar;

	public item_notificacion_modificador() {
		Design.read(this);
	}
}
