package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class item_mensaje_tema extends VerticalLayout {
	protected Image incluir_amigo_imga_btn;
	protected Image boton_like_mensaje_tema;
	protected Image notificar_a_moderador;
	protected Image bORRAR_MENSAJE_PROPIO;

	public item_mensaje_tema() {
		Design.read(this);
	}
}
