package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Logearse_ventana extends VerticalLayout {
	protected TextField text_email;
	protected PasswordField text_contrasena;
	protected Button iniciar_sesion_login;
	protected Button boton_registrarse;
	protected Label label_de_error;

	public Logearse_ventana() {
		Design.read(this);
	}
}
