package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class panel_informacion_user_ventana extends VerticalSplitPanel {
	protected HorizontalSplitPanel ventana_user;
	protected Panel etiqueta_user;
	protected Image imagen_perfil_usuario;
	protected Label nombre_perfil_texto;
	protected Label cantidad_amigos_texto;
	protected Label cantidad_mensajes_texto;
	protected Panel panel_usuario_logeado_actual;
	protected Image imagen_usuario_logeado_perfil;
	protected Label nombre_usuario_logeado;
	protected FormLayout formLayout_interfaz;
	protected Label texto_ultimos_mensajes;
	protected VerticalLayout lista_ultimos_mensajes;
	protected Button perfil_cambiar_contrasena;
	protected Button perfil_borrar_cuenta;
	protected Button perfil_incluir_amigo;
	protected Button boton_moderacion_reportes;
	protected Button perfil_cerrar_sesion;
	protected Button listaAmigos;
	protected Button perfil_historial_notificaciones_boton;
	protected Label correo_label_perfil;
	protected VerticalLayout descripcion_label;
	protected Label label_descripcion_perfil;
	protected Button boton_reportarPerfil;
	protected TextField field_motivo_de_reporte;

	public panel_informacion_user_ventana() {
		Design.read(this);
	}
}
