package com.example.MDS2_RodriguezSanchez;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class registrarse_ventana extends VerticalLayout {
	protected TextField text_nombre;
	protected TextField text_apellido;
	protected TextField correo_texto;
	protected PasswordField texto_contrasena;
	protected PasswordField contrasena_confirmacion_texto;
	protected Button boton_cancelar;
	protected Button boton_subir;
	protected Label label_errores;

	public registrarse_ventana() {
		Design.read(this);
	}
}
